FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 8081

# ENTRYPOINT fija el ejecutable
ENTRYPOINT ["python"]
# CMD define el argumento por defecto para ENTRYPOINT
CMD ["app.py"]
